---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fruits
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: infra-fruits
  path: ./apps/production
  prune: true
  sourceRef:
    kind: GitRepository
    name: fruits
  targetNamespace: default

