---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infra-fruits
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./crossplane/kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: infra-fruits
  targetNamespace: default

